// <auto-generated />
using System;
using CoreApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace HappyNews.Migrations
{
    [DbContext(typeof(DbContent))]
    [Migration("20190926201946_111")]
    partial class _111
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HappyNews.Models.Admins", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mail");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("HappyNews.Models.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentText");

                    b.Property<DateTime>("DateOfCreate");

                    b.Property<int?>("NewsId");

                    b.Property<int?>("UseriD");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.HasIndex("UseriD");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("HappyNews.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BodyNews");

                    b.Property<DateTime>("DateCreate");

                    b.Property<string>("IndexOfPosition");

                    b.Property<string>("NewsTitle");

                    b.Property<string>("Source");

                    b.HasKey("Id");

                    b.ToTable("Newses");
                });

            modelBuilder.Entity("HappyNews.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mail");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("HappyNews.Models.Comments", b =>
                {
                    b.HasOne("HappyNews.Models.News", "News")
                        .WithMany("Comments")
                        .HasForeignKey("NewsId");

                    b.HasOne("HappyNews.Models.Users", "User")
                        .WithMany("UserComments")
                        .HasForeignKey("UseriD");
                });
#pragma warning restore 612, 618
        }
    }
}
